spring:
  application:
    name : bookstore

  datasource:
    url:
    username:
    password:
    driver-class-name:

# 服务器配置
server:
  address: 0.0.0.0
  port: 8080

#项目物理地址
base-dir:
path:
  data-dir: ${base-dir}/data
  pst-dir: ${data-dir}/pst #持久数据
  tmp-dir: ${data-dir}/tmp #缓存数据

  image-dir: ${pst-dir}/images
  upload-dir: ${tmp-dir}/uploads
  log-dir: ${tmp-dir}/logs

jwt:
  secret:
  expiration: 3600000

ai:
  gemini:
    model: gemini-2.5-flash
    api-base-url:
    api-key:
    timeout: 30

  silicon-flow:
    api-key:
    api-base-url: https://api.siliconflow.cn/v1/chat/completions
    model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
    timeout: 30