spring:
  application:
    name : bookstore

  datasource:
    url:
    username:
    password:
    driver-class-name:

# 服务器配置
server:
  address: 0.0.0.0
  port: 8080

#项目物理地址
base-dir:

path:
  data-dir: ${base-dir}/data
  pst-dir: ${data-dir}/pst #持久数据
  tmp-dir: ${data-dir}/tmp #缓存数据

  image-dir: ${pst-dir}/images
  upload-dir: ${tmp-dir}/uploads
  log-dir: ${tmp-dir}/logs

jwt:
  secret: #jwt签名
  expiration: 36000

ai:
  openai:
    api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    api-base-url: https://api.openai.com/v1
    timeout: 30

  silicon-flow:
    api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    api-base-url: https://api.siliconflow.cn/v1/chat/completions
    timeout: 30